<?php

namespace App\Services\Booking;

use App\Models\Booking;
use Carbon\CarbonInterface;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Generates the `RS-YYMMDD-NNN` booking code: YYMMDD is the booking's
 * preferred pickup/delivery date, NNN is a per-date sequence shared by every
 * booking channel (online and walk-in alike), counted straight from the
 * database. Previously, online and walk-in bookings had two differently
 * shaped codes generated by two separate mechanisms, one of which (parsing
 * "the last booking's" code as if it were always `RS-####`) silently
 * produced garbage once that last booking happened to be the other shape.
 * One shape, one counter, closes that off entirely.
 *
 * Must run inside the caller's transaction: the advisory lock is
 * transaction-scoped and releases automatically at commit/rollback. A plain
 * `lockForUpdate()` on matching rows would not actually serialize two
 * concurrent creators for the same date (neither request updates those rows,
 * so both could read the same count), so this uses a Postgres advisory lock
 * instead.
 */
class BookingCodeGenerator
{
    private const LOCK_KEY = 918273645;

    public function next(CarbonInterface|string $preferredPickupAt): string
    {
        $date = Carbon::parse($preferredPickupAt);

        DB::select('select pg_advisory_xact_lock(?)', [self::LOCK_KEY]);

        $sequence = Booking::whereDate('preferred_pickup_at', $date->toDateString())->count() + 1;

        return 'RS-'.$date->format('ymd').'-'.str_pad((string) $sequence, 3, '0', STR_PAD_LEFT);
    }
}
